version: "3"
services:
  web:
    build: .
    ports:
      - "7097:7097"
    volumes:
      - .:/app
    working_dir: /app
    command:
      - python 
      - api.py
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 3
              capabilities: [gpu]
